name: governess
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  dio: ^4.0.6
  http: ^0.13.4
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  fluttertoast: ^8.0.9
  flutter_datetime_picker: ^1.5.1
  envify: ^2.0.2
  internet_connection_checker: ^0.0.1+3
  google_fonts: ^2.3.0
  pin_code_fields: ^7.4.0
  material_floating_search_bar: ^0.3.7
  image_picker: ^0.8.5+3
  camera: ^0.9.7+1
  json_annotation: ^4.5.0
 
  


 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  hive_generator: ^1.1.2
  envify_generator: ^2.0.2
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^6.2.0


flutter_icons:
  android: true
  remove_alpha_ios: true
  
  ios: true
  image_path: "assets/images/governessLogo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
